// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.EmployeeOnboarding dS_WorkflowUserTask_GetEmployee_OnboardingContext(IContext context, system.proxies.WorkflowUserTask _userTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserTask", _userTask == null ? null : _userTask.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_WorkflowUserTask_GetEmployee_OnboardingContext").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.EmployeeOnboarding.initialize(context, result);
	}
}