// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EmployeeOnboarding
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeOnboardingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmployeeOnboarding";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		WFH("WFH"),
		FirstDay("FirstDay"),
		PhoneModel("PhoneModel"),
		LaptopModel("LaptopModel");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeOnboarding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.EmployeeOnboarding"));
	}

	protected EmployeeOnboarding(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeOnboardingMendixObject)
	{
		if (employeeOnboardingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.EmployeeOnboarding", employeeOnboardingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.EmployeeOnboarding");

		this.employeeOnboardingMendixObject = employeeOnboardingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmployeeOnboarding.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.EmployeeOnboarding initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.EmployeeOnboarding.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.EmployeeOnboarding initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmployeeOnboarding(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmployeeOnboarding load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmployeeOnboarding.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.EmployeeOnboarding> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.EmployeeOnboarding> result = new java.util.ArrayList<myfirstmodule.proxies.EmployeeOnboarding>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.EmployeeOnboarding" + xpathConstraint))
			result.add(myfirstmodule.proxies.EmployeeOnboarding.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of WFH
	 */
	public final java.lang.Boolean getWFH()
	{
		return getWFH(getContext());
	}

	/**
	 * @param context
	 * @return value of WFH
	 */
	public final java.lang.Boolean getWFH(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WFH.toString());
	}

	/**
	 * Set value of WFH
	 * @param wfh
	 */
	public final void setWFH(java.lang.Boolean wfh)
	{
		setWFH(getContext(), wfh);
	}

	/**
	 * Set value of WFH
	 * @param context
	 * @param wfh
	 */
	public final void setWFH(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean wfh)
	{
		getMendixObject().setValue(context, MemberNames.WFH.toString(), wfh);
	}

	/**
	 * @return value of FirstDay
	 */
	public final java.util.Date getFirstDay()
	{
		return getFirstDay(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstDay
	 */
	public final java.util.Date getFirstDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.FirstDay.toString());
	}

	/**
	 * Set value of FirstDay
	 * @param firstday
	 */
	public final void setFirstDay(java.util.Date firstday)
	{
		setFirstDay(getContext(), firstday);
	}

	/**
	 * Set value of FirstDay
	 * @param context
	 * @param firstday
	 */
	public final void setFirstDay(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date firstday)
	{
		getMendixObject().setValue(context, MemberNames.FirstDay.toString(), firstday);
	}

	/**
	 * Set value of PhoneModel
	 * @param phonemodel
	 */
	public final myfirstmodule.proxies.PhoneModel getPhoneModel()
	{
		return getPhoneModel(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneModel
	 */
	public final myfirstmodule.proxies.PhoneModel getPhoneModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PhoneModel.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.PhoneModel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PhoneModel
	 * @param phonemodel
	 */
	public final void setPhoneModel(myfirstmodule.proxies.PhoneModel phonemodel)
	{
		setPhoneModel(getContext(), phonemodel);
	}

	/**
	 * Set value of PhoneModel
	 * @param context
	 * @param phonemodel
	 */
	public final void setPhoneModel(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PhoneModel phonemodel)
	{
		if (phonemodel != null)
			getMendixObject().setValue(context, MemberNames.PhoneModel.toString(), phonemodel.toString());
		else
			getMendixObject().setValue(context, MemberNames.PhoneModel.toString(), null);
	}

	/**
	 * Set value of LaptopModel
	 * @param laptopmodel
	 */
	public final myfirstmodule.proxies.LaptopModel getLaptopModel()
	{
		return getLaptopModel(getContext());
	}

	/**
	 * @param context
	 * @return value of LaptopModel
	 */
	public final myfirstmodule.proxies.LaptopModel getLaptopModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LaptopModel.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.LaptopModel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LaptopModel
	 * @param laptopmodel
	 */
	public final void setLaptopModel(myfirstmodule.proxies.LaptopModel laptopmodel)
	{
		setLaptopModel(getContext(), laptopmodel);
	}

	/**
	 * Set value of LaptopModel
	 * @param context
	 * @param laptopmodel
	 */
	public final void setLaptopModel(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.LaptopModel laptopmodel)
	{
		if (laptopmodel != null)
			getMendixObject().setValue(context, MemberNames.LaptopModel.toString(), laptopmodel.toString());
		else
			getMendixObject().setValue(context, MemberNames.LaptopModel.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeOnboardingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmployeeOnboarding that = (myfirstmodule.proxies.EmployeeOnboarding) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.EmployeeOnboarding";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
